---
title: "<i class='bi bi-cpu'></i> Λογισμικό και Δεδομένα"
description: "Το μέρος στο οποίο θα μοιράζομαι τα πακέτα μου στην R. Επίσης, θα ανεβάζω το ορισμένα εξορυγμένα δεδομένα από διάφορες ιστοσελίδες"
link-external-newwindow: true
page-layout: full
comments: false
title-block-banner: true
css: ../assets/styles/custom-style.css
listing:
  - id: rpackages
    type: custom
    template: _listing_r.ejs
    contents: "r-packages/**/index.qmd"
    include:
      lang: el
  - id: datasets
    type: custom
    template: _listing.ejs
    contents: "datasets/**/index.qmd"
    include:
      lang: el
toc: true
format: 
  html:
    page-layout: full
    anchor-sections: false
---


## R πακέτα

Εξειδικευμένο λογισμικό για χρήστες που δουλεύουν αποκλειστικά με τη γλώσσα προγραμματισμού R. Έχω πάρα πολλά να μάθω ακόμα, οπότε αναμένεται να δημοσιεύσω αρχικά μόνο πακέτα δεδομένων. Έχω κάποιες καλές ιδέες και για πιο σύνθετα πακέτα, αλλά αναμένεται να ασχοληθώ με αυτά από το 2026 ... 😀

::: {#rpackages}
:::

## Εξόρυξη δεδομένων

Για την ανάλυση δεδομένων κάτι που είναι απαραίτητο είναι τα δεδομένα. Ωστόσο, σπάνια είναι όλα όσα επιθυμούμε ελεύθερα, διαθέσιμα και οργανωμένα. Έτσι πρέπει να εξάγουμε τις απαραίτητες πληροφορίες από διάφορες πηγές. Αυτά είναι μερικά projects που εξάγω δεδομένα από διάφορες ιστοσελίδες, ώστε να τα αναλύσω σε κάποια άρθρα μου. Απλά αν σε ενδιαφέρει κάποιο σύνολο δεδομένων από τα παρακάτω μπορείς να το κατεβάσεις και να κάνεις τη δική σου ανάλυση, δίχως να χρειάζεσαι να χρησιμοποιήσεις R. Μπορείτε να διαβάσετε και το αντίστοιχο άρθρο για περισσότερες τεχνικές λεπτομέρειες.


::: {#datasets}
:::


