---
title: "<i class='bi bi-paperclip'></i> My Resume"
description: "Read my curicculum vitae online"
css: ../assets/styles/custom-style.css
title-block-banner: true
format:
  html:
    comments: false
    anchor-sections: false
    toc: false
    page-layout: full
    grid:
      content-mode: standard
      sidebar-width: 0px
      margin-width: 0px
---

<p class="text-center p-lg-4 p-0">
In case you want to download my CV, you can get it by clicking this button: 
<a href="https://github.com/stesiam/typstCV/releases/download/v1.0/cvDS-eng.pdf" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label="Button to download my resume in pdf format - the same as the page you read"><i class="bi bi-download"></i> Download my Curriculum Vitae (CV)</a>
</p>
<hr>

<h2 class="p-0 g-0 border-0 m-0">STESIAM</h2>
<p class="fs-5 fst-italic">Statistics Graduate</p>

::: {.header-contact .d-flex .flex-wrap .justify-content-center .gap-4 .mb-4}
<p class="d-flex flex-column flex-lg-row gap-2 gap-lg-4">
<span><i class="bi bi-envelope"></i> stesiam [at] proton [dot] me</span>
<span><i class="bi bi-link-45deg"></i> <a href="https://stesiam.com/">stesiam.com</a></span>
<span><i class="bi bi-github"></i> <a href="https://github.com/stesiam">@stesiam</a></span>
<span><i class="bi bi-bluesky"></i> <a href="https://bsky.app/profile/stesiam.bsky.social">@stesiam</a></span>
<span><i class="bi bi-geo-alt"></i> Athens, Greece</span>
</p>
:::


My name is Stelios and I live in Athens. I am a recent graduate of the Department of [Statistics and Insurance Department](https://www.unipi.gr/en/department-of-statistics-and-insurance-science/) at the University of
Piraeus. I have considerable familiarity with technology and various statistical packages and programs, as well as with R, a programming
language specializing in data analysis. At the moment, I would like to improve and apply my knowledge in Statistics and related software
in a professional environment. I have no work experience, but I am willing to work, learn, and develop my skills. I invite you to take a
look at my projects and activities to better understand my background and level of knowledge.

::: {.grid}

::: {.g-col-12 .g-col-md-8}

### <i class="bi bi-briefcase"></i> PROJECTS {.section-title}

#### Scraping data 
<p class="small"><a href="https://github.com/stesiam/insuranceRegister" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-github"></i> GitHub Repo</a></p>

A project in which I retrieved the complete registry of (re)insurance companies
operating in Greece. The list was scraped from the website of the Bank of Greece.
Traditional scraping methods did not work on this table, and for this reason, in
addition to the {rvest} package, the {RSelenium} package was also used.

#### Data Visualization
<p class="small"><a href="https://stesiam.com/gallery/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-github"></i> GitHub Repo</a></p>

In recent years, I have been practicing the production of charts using R and various
packages. For instance, since 2022 I have created many 'static' charts with the
{ggplot2} package, and some of them have been posted on my website

#### Data Analysis
<p class="small"><a href="https://stesiam.com/posts/forecasting-greek-unemployment/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-link-45deg"></i> Article URL</a></p>

A time series analysis for the case of unemployment in Greece, in which I attempt to
find a model that predicts the future course of unemployment in Greece. I study the
time series for stationarity, the presence of structural breaks, and I primarily fit
ARIMA and Exponential Smoothing (ETS) models in order to forecast short-term
unemployment over the next six months

#### ML Web Applications
<p class="small"><a href="https://stesiam.shinyapps.io/web-dev-wages/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-link-45deg"></i> Web App URL</a></p>

Based on data from a relevant survey on developers' salaries, I built a predictive
regression model to forecast a developer's salary. The model is based on features
such as years of programming experience, the employer's country, and others. The
accuracy of the model can be characterized as moderate due to the relatively small
sample size (800 individuals).


### <i class="bi bi-mortarboard"></i> EDUCATION {.section-title}
- **BSc. in Statistics and Insurance Science**<br>
<i class="bi bi-building"></i> [University of Piraeus](#)<br>
<i class="bi bi-calendar-check"></i> *Graduated at June, 2025*

<p>During my studies, I was taught several courses related to Statistics as well as
Statistical Software. Indicatively, I will mention the courses of:<br>
- Probabilities<br>
- Statistics: Estimation Theory<br>
- Non-parametric Statistics<br>
- Sampling and <br>
- Statistical Programs using R <br>
</p>
:::

::: {.g-col-12 .g-col-md-4 .sidebar-column}

### <i class="bi bi-code-slash"></i> PROGRAMMING {.section-title}
- R (Rstats)
- SQL (dbplyr)
- Python
- JavaScript (DOM)

### <i class="bi bi-tags"></i> SKILLS {.section-title}
- Linux (Ubuntu)
- Git
- LaTeX
- Typst
- Quarto
- HTML/CSS
- Docker
- Web apps (Shiny)
- API (plumber / FastAPI)
- Data analysis
- Machine learning

### <i class="bi bi-tags"></i> FAMILIARITY WITH R PACKAGES {.section-title}

- dplyr
- tidyr
- ggplot2
- stringr
- tidymodels
- tidyverts
- rvest
- RSelenium

### <i class="bi bi-tags"></i> PROGRAMS I USE {.section-title}

- RStudio - Positron - VSCode

### <i class="bi bi-translate"></i>LANGUAGES {.section-title}
- Greek (native)
- English (C2)

:::

:::


