---
title: "Το βιογραφικό μου"
description: "Διαβάστε το βιογραφικό μου διαδικτυακά"
format:
  html:
    comments: false
    anchor-sections: false
    toc: false
    page-layout: full
    grid:
      content-mode: standard
      sidebar-width: 0px
      margin-width: 0px
---

<p class="text-center p-lg-4 p-0">
Σε περίπτωση που θέλετε να αποθηκεύσετε το βιογραφικό μου, μπορείτε να το κατεβάσετε σε μορφή pdf πατώντας το παρακάτω κουμπί: 
<a href="https://github.com/stesiam/cvDSen/blob/main/index.pdf" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label="Button to download my resume in pdf format - the same as the page you read"><i class="bi bi-download"></i> Κατέβασε το βιογραφικό μου</a>
</p>
<hr>

<h2 class="p-0 g-0 border-0 m-0">STESIAM</h2>
<p class="fs-5 fst-italic">Απόφοιτος Στατιστικής</p>


::: {.header-contact .d-flex .flex-wrap .justify-content-center .gap-4 .mb-4}
<p class="d-flex flex-column flex-lg-row gap-2 gap-lg-4">
<span><i class="bi bi-envelope"></i> stesiam [at] proton [dot] me</span>
<span><i class="bi bi-link-45deg"></i> <a href="https://stesiam.com/">stesiam.com</a></span>
<span><i class="bi bi-github"></i> <a href="https://github.com/stesiam">@stesiam</a></span>
<span><i class="bi bi-bluesky"></i> <a href="https://bsky.app/profile/stesiam.bsky.social">@stesiam</a></span>
<span><i class="bi bi-geo-alt"></i> Αθήνα, Ελλάδα</span>
</p>
:::
Με λένε Στέλιο και μένω στην Αθήνα. Είμαι πρόσφατος απόφοιτος του τμήματος [Στατιστικής και Ασφαλιστικής Επιστήμης](https://www.unipi.gr/tmima-statistikis-kai-asfalistikis-epistimis/) του Πανεπιστημίου Πειραιά. Διαθέτω αρκετά μεγάλη εξοικείωση με τη τεχνολογία και με διάφορα στατιστικά πακέτα - προγράμματα, καθώς και με την R, μία γλώσσα προγραμματισμού
που εξειδικεύεται στην ανάλυση δεδομένων. Αυτή τη στιγμή θα ήθελα να βελτιώσω και να αξιοποιήσω τις όποιες γνώσεις μου στη Στατιστική και σε αντίστοιχο λογισμικό σε ένα εργασιακό περιβάλλον. Δεν έχω εργασιακή εμπειρία αλλά είμαι πρόθυμος να εργαστώ, να μάθω και να αναπτύξω τις δεξιότητές μου. Σας προσκαλώ να ρίξετε και μία ματιά στις δραστηριότητές - project μου για να κατανοήσετε το υπόβαθρό και το επίπεδο των γνώσεών μου.


::: {.grid}

::: {.g-col-12 .g-col-md-8}

### <i class="bi bi-briefcase"></i> ΔΡΑΣΤΗΡΙΟΤΗΤΕΣ {.section-title}

#### Εξαγωγή δεδομένων
<p class="small"><a href="https://github.com/stesiam/insuranceRegister" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-github"></i> Αποθετήριο GitHub</a></p>

Μία εργασία στην οποία ανέκτησα το σύνολο του μητρώου των (αντ)ασφαλιστικών εταιρειών που λειτουργούν στην Ελλάδα. Η λίστα εξορύχθηκε από την ιστοσελίδα της Τράπεζας της Ελλάδος που είναι και η εποπτεύοσα αρχή αυτού του τύπου των εταιρειών. Οι παραδοσιακές μέθοδοι εξόρυξης δεν λειτουργούσαν σε αυτό τοξ πίνακα και για αυτό εκτός από το πακέτο `{rvest}` χρησιμοποιήθηκε και το πακέτο `{RSelenium}`. Τα εξορυγμένα δεδομένα αποθηκεύτηκαν και  «τακτοποιημένη» μορφή με βάση το όνομα της εταιρείας, το είδος της ασφαλιστικής εταιρείας, αν είναι ενεργή και αναλαμβάνει ασφαλιστικές εργασίες μέχρι και σήμερα, τη χώρα που εδρεύει και την διεύθυνση των γραφείων της. 

#### Οπτικοποίηση δεδομένων
<p class="small"><a href="https://stesiam.com/el/gallery" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-github"></i> Στατικά διαγράμματα</a></p>
<p class="small"><a href="https://stesiam.com/el/gallery/interactive-charts/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-github"></i> Διαδραστικά διαγράμματα</a></p>

Τα τελευταία χρόνια εξασκούμαι στην παραγωγή γραφημάτων με τη χρήση της R και διάφορων πακέτων. Ενδεικτικά, από το 2022 έχω κατασκευάσει πολλά «στατικά» γραφήματα με το πακέτο `{ggplot2}` και μέρος αυτών τα έχω αναρτήσει στην ισοτσελίδα μου. Από το 2024 πειρατίζομαι και με τη κατασκευή διαδραστικών και προσβάσιμων γραφημάτων με τη βοήθεια των πακέτων `{highcharter}`, `{echarts4r}` και `{ggplotly}`. Η πλειοψηφία αυτών των γραφημάτων έγινε υπό το πρίσμα γνωστών «προκλήσεων» στην R κοινότητα, όπως το [#TidyTuesday](https://github.com/rfordatascience/tidytuesday) και το [#30DayChartChallenge](https://github.com/30DayChartChallenge), ενώ τα υπόλοιπα είναι συνήθως από άρθρα που έχω γράψει στην ιστοσελίδα μου.

#### Ανάλυση δεδομένων
<p class="small"><a href="https://stesiam.com/el/posts/forecasting-greek-unemployment/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-link-45deg"></i> Σύνδεσμος πρώτου άρθρου</a></p>
<p class="small"><a href="https://stesiam.com/posts/el/kaggle-greek-community/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-link-45deg"></i> Σύνδεσμος δεύτερου άρθρου</a></p>

Στο πρώτο άρθρο γίνεται μία ανάλυση χρονοσειρών για τη περίπτωση της ανεργίας στην Ελλάδα και προσπαθώ να βρω ένα μοντέλο που να προβλέπει καλύτερα τη μελλοντική πορεία της ανεργίας στην Ελλάδα. Μελετάω τις χρονοσειρές για σταιμότητα, ύπαρξη τομών (breaks) και προσαρμόζω κυρίως κάποια μοντέλα ARIMA και Εκθετικής Εξομάλυνσης (ETS) για να βρω τη βραχυχρόνια ανεργία εντός έξι μηνών.

Το δεύτερο άρθρο αποτελεί μία απλή περιγραφική ανάλυση της γνωστής έρευνας πυο διεξήγαγε το Kaggle το 2022. Σε αυτό το άρθρο προσπαθώ να συγκρίνω τα χαρακτηριστικά των Ελλήνων χρηστών με των υπολοίπων χωρών, καθώς και τους χρήστες R  με τους χρήστες Python. Η ανάλυση εξήγαγε κάποια ενδαιφέροντα στοιχεία όπως την σημνατικά αναλογικά  χαμηλή εκπροσώποηση αυτών των ομάδων. Επιπλεόν,  η Ελλάδα αλλά και η κοινότητα της R μοιράζονται κάποια κοινά χαρακτηριστικά όπως η μεγαλύτερη ηλικία, μεγαλύτερη εργασιακή εμπειρία κτλ. Τέλος, στην κοινότητα υπάρχει μία χαμηλή εκπροσώπηση των γυναικών με την Ελλάδα να έχει χαμηλότερη εκπροσώπηση στις γυναίκες ακόμα και από το μέσο όρο των υπολοίπων χωρών.

#### Ηλεκτρονικές εφαρμογές
<p class="small"><a href="https://stesiam.shinyapps.io/Dev-Wages-App/" class="btn  btn-primary btn-rounded btn-sm" target="_blank" aria-label=""><i class="bi bi-link-45deg"></i> Σύνδεσμος εφαρμογής</a></p>

Βασιζόμενος σε δεδομένα σχετικής έρευνας για τους μισθούς των προγραμματιστών, ξεκινάω να τακτοποιώ τα δεδομένα για να κατασκευάσω ένα προβλεπτικό μοντέλο παλινδρόμησης. Ο στόχος μου είναι να προβλέψω τον μισθό ενός προγραμματιστή to build a regression (XGBoost) model with tidymodels. Η εφαρμογή μπορεί να προεβλέψει τον μισθό ενός προγραμματιστή με βάσει κάποια χαρακτηριστικά, όπως τα έτης εμπειρίας με τον προγραμματισμό, τη χώρα του εργοδότη κα. Το μοντέλο κατασκευάστηκε με βάσει τον αλγόριθμο XGBoost και με τη βοήθεια της σουίτας πακέτων `{tidymodels}`. Η ακρίβεια του μοντέλου μπορεί να χαρακτηριστεί μέτρια λόγω του μικρού σχετικά δείγματος (800 άτομα). Μικρές βελτιώσεις ως προς την ακρίβεια του μοντέλου έχουν παραατηρηθεί με επιπλέον ενέργειας όπως η αύξηση των grids και η σύνθεση - συνδυασμός ορισμένων μοντέλων.

### <i class="bi bi-mortarboard"></i> ΕΚΠΑΙΔΕΥΣΗ {.section-title}
- **Πτυχίο στη Στατιστική και Ασφαλιστική Επιστήμη**<br>
<i class="bi bi-building"></i> Πανεπιστήμιο Πειραιά<br>
<i class="bi bi-calendar-check"></i> *Αποφοίτησα τον Ιούνιο, 2025*

Κατά τη διάρκεια των σπουδών μου διδάχθηκα αρκετά μαθήματα σχετικά με τη Στατιστική. Αναφέρονται
ενδεικτικά τα εξής: <br>
<ul>
<li>Στατιστική: Έλεγχος Υποθέσεων</li>
<li> Μη Παραμετρική Στατιστική</li>
<li> Στατιστικά Προγράμματα I / II (SPSS/R)</li>
<li> Δειγματοληψία</li>
</ul>
Τέλος, μέσω των σπουδών μου είχα μία έκθεση σε διάφορα στατιστικά προγράμματα (όπως το SPSS) ή γλώσσες
προγραμματισμού που δίνουν έμφαση στην ανάλυση δεδομένων (όπως η R).
:::

::: {.g-col-12 .g-col-md-4 .sidebar-column}


### <i class="bi bi-bar-chart-line"></i> ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ {.section-title}
- R (Rstats)
- SQL (dbplyr)
- JavaScript (DOM)
- Python

### <i class="bi bi-tags"></i> ΔΕΞΙΟΤΗΤΕΣ {.section-title}
- Linux (Ubuntu)
- Git
- LaTeX
- HTML/CSS
- Docker
- Web apps (Shiny)
- API (plumber / FastAPI)
- Ανάλυση δεδομένων
- Μηχανική μάθηση

### <i class="bi bi-diagram-3"></i> ΓΛΩΣΣΕΣ {.section-title}
- Ελληνικά (μητρική)
- Αγγλικά (C2)

:::

:::
