---
title: "<i class='bi bi-code-slash'></i> Εφαρμογές"
description: "Οι εφαρμογές που έχω φτιάξει χρησιμοποιώντας το πακέτο Shiny. Οι περισσότερες φιλοξενούνται στο shinyapps.io το οποίο έχει περιορισμούς επισκεψιμότητας. Τέλος, έχω πειραματιστεί λίγο και με τη δημιουργία APIs κυρίως για τη χρήση μοντέλων μηχανικής μάθησης. "
link-external-newwindow: true
page-layout: full
comments: false
title-block-banner: true
css: ["s.css",  "../assets/styles/custom-style.css"]
listing:
  - id: dashboards
    type: custom
    template: list.ejs
    contents: "dashboards/**/index.qmd"
    sort: "order asc"
    include:
      lang: el
  
  - id: shiny_web_apps
    type: custom
    template: list.ejs
    contents: "apps/**/index.qmd"
    sort: "order asc"
    include:
      lang: el

  - id: apis
    type: custom
    template: list.ejs
    contents: "apis/**/index.qmd"
    sort: "order asc"
    include:
      lang: el
toc: true
format: 
  html:
    page-layout: full
    anchor-sections: true
---

```{=html}
<style>
h3 a{
  display: none;
}
</style>
```

## <i class="bi bi-activity"></i> Ταμπλό - Dashboards

Διαδραστικοί πίνακες ελέγχου που συνοψίζουν και οπτικοποιούν δεδομένα χρησιμοποιώντας γραφήματα, πίνακες και στατιστικά. Βοηθά στην γρήγορη και οργανωμένη ανασκόπηση της κατάστασης ή της οντότητας στην οποία αναφέρεται

::: {#dashboards}
:::

## <i class="bi bi-menu-app"></i> Ηλεκτρονικές Εφαρμογές

Διαδικτυακές εφαρμογές που ξεπερνούν τη λογική των dashboards και της απλής περιγραφικής στατιστικής, επιτρέποντας στον χρήστη να αλληλεπιδρά ενεργά και να εκτελεί συγκεκριμένες ενέργειες. Ιδιαίτερη έμφαση δίνεται σε εφαρμογές μηχανικής μάθησης, όπου η εφαρμογή παράγει αποτελέσματα ή προβλέψεις με βάση ένα εκπαιδευμένο μοντέλο και τις εισόδους του χρήστη.

::: {#shiny_web_apps}
:::


## <i class="bi bi-braces"></i> APIs

APIs που εκθέτουν στατιστικές διαδικασίες, υπολογισμούς ή μοντέλα μηχανικής μάθησης χωρίς UI, ώστε να μπορούν να αξιοποιηθούν από άλλες εφαρμογές.

::: {#apis}
:::

