---
title: "Σύνοψη Κατανομών"
description: "Μία λίστα με τις συνήθεις κατανομές και τα χαρακτηριστικά τους"
svgIcon: "<svg width='48' height='48' viewBox='0 0 24 24' fill='currentColor' class='text-primary'>
              <path d='M3 3v18h18V3H3zm16 16H5V5h14v14zm-8-3h6v2h-6v-2zm0-4h6v2h-6v-2zm0-4h6v2h-6V8z'/>
          </svg>"
          
links:
  - url: https://github.com/stesiam/distributions-poster/releases/download/v1.0.0/distributions-poster-el.pdf
    icon: bi-download
    text: "Κατέβασέ το!"

posterText: "Διάβασε το άρθρο"

format: html
---

## Τι είναι οι κατανομές;

Μία βασική έννοια στη Στατιστική είναι αυτή των κατανομών. Με δεδομένο ότι δεν είναι μία λέξη που χρησιμοποιείται ευρέως στη καθημερινότητα ενδεχομένως με το που την ακούσει κάποιος να του προκαλέσει μία απορία ή μία σύγχηση για το ότι είναι κάποιος περίπλοκος όρος. Στη καθομιλουμένη ίσως να έχουμε χρησιμοποήσει τον όρο όταν αναφερόμαστε πώς κατανέμουμε, δηλαδή μοιράζουμε - μία ομάδα ανθρώπων. Παραδείγματος χάριν:

- τα παιδιά ενός σχολείου σε τάξεις
- τα ύψη των ανθρώπων στο γενικό πληθυσμό
- 

Άρα με τον όρο *κατανομές* προσπαθούμε να περιγράψουμε τον τρόπο με τον όποίο μοιράζεται το δείγμα ή ο πληθυσμός που εξετάζω. Μία απλοϊκή ανάλυση είναι με βασικά μέτρα θέσης και διασποράς και κύρτωσης.






## Διακριτές κατανομές

Οι διακριτές κατανομές είναι όσες κατανομές οι τυχαίες μεταβλητές μας (άγνωστες τιμές που εκτιμώ)

### Bernoulli

Τα δεδομένα που ακολουθούν την κατανομή Bernoulli ($X \sim Bernoulli(p)$) έχει μόνο μία παράμετρο $p$ η οποία παίρνει τιμές μηδέν ή ένα ($p \in \{0,1\}$). 
Έχει συνάρτηση πιθανότητας:

$$
f(x) = qp
$$


## Συνεχείς κατανομές

Από την άλλη μεριά οι συνεχείς κατανομές είναι οι κατανομές που που μπορούν να έχουν ως τιμές δεκαδικές τιμές, σε ατν´θεση με τις διακριτές. Έτσι είναι αρκετά χρήσιμες σε μελέτη αριθμητικών μεγεθών που δεν περιγράφονται απαρείτητα από ακέραιους αριθμούς:

- Βαθμοί Κελσίου
- Ύψος
- Ποσοστό ανεργίας σε μία χώρα

Όλα αυτά είναι παραδείγματα που το δεκαδικό τους μέρος θεωρείται σημαντικό.

### 
